# Custom Language File for Launcher Customizer

[ejs.app]
title = "DIA ESCAPE"

[ejs.landing]
mediaGitHubURL = "https://skhcs.com/diaescape"
mediaChzzkURL = "https://chzzk.naver.com/da504b5309f9b4eee7e9022690e215d1"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "DIA ESCAPE"
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."